#!/bin/bash
#
#******************************************************************************
# make_dox (XPCCUT)
#------------------------------------------------------------------------------
##
# \file       	make_dox
# \library    	XPCCUT
# \author     	Chris Ahlstrom
# \date       	2011-12-28
# \update     	2018-11-12
# \version    	$Revision$
# \license    	$XPC_SUITE_GPL_LICENSE$
#
#     This file creates the doxygen documentation desired, by changing to
#     the original directory, running doxygen, and moving the results back
#     to the original directory.
#
#     This is our way of handling out-of-source builds of documentation,
#     without getting into the complexities of GNU Autotools method of
#     supporting Doxygen.
#
#     Apart from the complexity of this work, another reason for using a
#     script, instead of putting the code in Makefile.am, is that we need
#     some bash features (e.g. pushd/popd), and also need to be able to run
#     only one instance of bash -- 'make' runs each line of code on its own
#     instance.
#
#        -  userman.  Make the user manual; leave out the design
#           documentation.
#
# Manual run for documentation:
#
#     The automatic build of documentation seems to be broken.  For now, from
#     the project root, just run "./doc/dox/make_dox" to build the user manual.
#
#------------------------------------------------------------------------------

DOXYGEN="doxygen"

if [ "$1" == "clean" ] ; then
   rm -rf html
   rm -rf latex
   rm -f *.log
else
   echo "$DOXYGEN doxygen.cfg > dox-user-progress.log 2> dox-user-errors.log ..."
   $DOXYGEN doxygen.cfg > dox-user-progress.log 2> dox-user-errors.log
   if [ $? == 0 ] ; then
      pushd latex
      make
      cp refman.pdf ../../xpc_c_cpp_unit_test_library.pdf
   else
      echo "Error.  Check the log files."
   fi
fi

#******************************************************************************
# make_dox (XPCCUT)
#------------------------------------------------------------------------------
# vim: ts=3 sw=3 et ft=sh
#------------------------------------------------------------------------------
